### ISSUE TITLE
Option to ignore Certificats verification?

### ISSUE THREAD

**Issue by gaumondp** [merzilla/inm_googlesitemap#1]
I was not able to crawl my site under HTTPS (worked for another one under HTTP).

This could be because of certificats, right? I checked the original librairie for any hints about something similar to GUZZLE handling,without success. I'm talking about  http://docs.guzzlephp.org/en/latest/request-options.html#verify

I really like the approach of your extension with a site with 10 000 pages it's way more efficient...

**Comment by merzilla** [comment]
Hi @gaumondp 

hmm.. we have never had any problems with our own faked certificates on our staging servers running HTTPS. The PHPCrawl library uses a `stream_socket_client` for the connection, checking if openssl ist installed.
Can you see anything in the sys_log in the backend log module?

**Comment by merzilla** [comment]
No more answers or discussions... so I will close this.
